INSERT INTO `responses` (`id`, `nama`, `tanggapan`, `sentiment`) VALUES
(1, 'Haidar Hendri', 'Ah aplikasinya gitu doang, coba ada fitur fitur lainnya kayak info info seputaran pajak.', 'N'),
(2, 'Asih', 'Terlalu dekat klo 1 bulan', 'N'),
(3, 'Dwi Chantika', 'Motor saya sudah bayar tapi kenapa tetap dapat wa nya ya', 'N'),
(4, 'FIlga Harry S', 'Parah ah nih ga di update update. Masih lemot niiih', 'N'),
(5, 'Lukman', 'Bukannya hanya akam buang2 dana', 'N'),
(6, 'Sulistyono', 'Saya udah coba daftar berkali kali ga bisa bisa.', 'N'),
(7, 'Tembang Kasmaran', 'Pajak naik terus tapi jalanannya bolong2', 'N'),
(8, 'Bagyo Mulia Motor', 'Tolong dong pelayanan di kantronya ditingkatkan lagi.', 'N'),
(9, 'Hendro', 'Kenapa tidak ada samsat keliling lagi?', 'N'),
(10, 'Widodo Selamet', 'Tolong pelayanan di kantor dipercepat, diminta bayar lalau lama saat bayar ya sama aja', 'N'),
(11, 'Elly S Susanto', 'Lebih baik meningkatkan samsat keliling nya', 'N'),
(12, 'Dedy Cahya', 'Nggk terlalu membantu, karna info pesannya tenggelam dengan pesan lainnya', 'N'),
(13, 'Hartono Nanggulan', 'Bagi saya ini tidak terlalu berpengaruh, karna saya membayar dengan tepat waktu setiap tahunnya', 'N'),
(14, 'Cica Adjah', 'Kurang membantu jika pengingat hanya dikirimkan 1 bulan sebelumnya hehe', 'N'),
(15, 'Lukman', 'Nggk membantu banget sih', 'N'),
(16, 'Ratihwulansari', 'Tidak membantu, karna jarang punya kuota, jadi sama aja kadang telat bayar', 'N'),
(17, 'Kendhil Ajus', 'Tanggal pembayaran saya belum sesuai, jadiya nggk membantu', 'N'),
(18, 'Wiyono', 'Pesan pengingat terlalu jauh dengan tanggal pembayaran, tidak membantu', 'N'),
(19, 'Agus Rohmadi', 'Tidak membantu, pesan pengingat jauh tenggelam dengan pesan lainnya', 'N'),
(20, 'Mugi', 'Klo yg gak punya Wa', 'N'),
(21, 'Rafi', 'Ngingatin jangan cuma sekali', 'N'),
(22, 'Guntur jati', 'Nek aku kurang suka, karena akan lebih oke dibuatkan aplikasi sekalian', 'N'),
(23, 'Retnu sari', 'Kurang beberapa hal seperti bisa untuk menanyakan jumlah dan tanggal pajak kendaraan', 'N'),
(24, 'Clone 21?', 'Sebetulnya ga penting applikasi iini kalau pada sadar bayar pajak.', 'N'),
(25, 'Clone 24', 'Alah giliran suruh bayar pajak aja ldirawat banget aplikasinya. Jalanan jelek benerin noh!', 'N'),
(26, 'Clone 25', 'mungkin bisa ditingaktkan kembali terkait frekuensi mengingatkannya', 'N'),
(27, 'Supri', 'Kurang setuju Krn TDK semua wajib pajak mmemiliki wa', 'N'),
(28, 'Sasongko', '2bln sebelumnya', 'N'),
(29, 'Wahit', '??', 'N'),
(30, 'Peter Sriyana', 'Giliran pajak diingetin terus, tapi hak masyarakat susah', 'N'),
(31, 'Siham Siham', 'Jangan sampe ada korupsi ya', 'N'),
(32, 'Dasuki Kijingan', 'Tidak membantu banget. pengingatnya terlalu jauh dengan jadwal pembayaran e', 'N'),
(33, 'Tika Dewi Putri', 'WA kadang terlalu penuh pesan. pengingat nggk membantu jane', 'N'),
(34, 'Kanggo Riko Santos', 'Perbaiki lagi', 'N'),
(35, 'Qodrat BerMunajat', 'Tanpa pengingat juga udah ingat. Tidak membantu banget', 'N'),
(36, 'Bintangmuda', 'Stop monopoli, waktunya perbaiki aksi', 'N'),
(37, 'Hary Ant', 'Rumongso mbayar rutin kok', 'N'),
(38, 'Abdul Jafar', 'Pertingkatkan aksi bukan hanya dengan mengingatkan pembayaran. Smangat memperbaiki', 'N'),
(39, 'Ryan Gab', 'Ojo mung ngingetke tok, aku yo tetep mbayar', 'N'),
(40, 'Muhammad Tajudin Mahkota', 'Rajin pajak tpi rakyat blm merdeka', 'N'),
(41, 'Wanto Mega', 'NKRI harga mati', 'N'),
(42, 'Zeina Tri', 'Pembayaran tepat waktu apakah ada reward?', 'N'),
(43, 'Sri Rias', 'Pajak terlalu tinggi, korupsi tak henti', 'N'),
(44, 'Jamadi', 'pajak aja diingetin woww', 'N'),
(45, 'Yuli Purnomo', 'Kenapa pengingat hanya satu kali? tidak membantu', 'N'),
(46, 'Hafiz Putra', 'Reminder hanya sekali, tidak maksimal', 'N'),
(47, 'Wong Claten', 'tidak membantu, sorry', 'N'),
(48, 'Dhiesta Atalla', 'Ngingetin cepet, tapi pelayanan lambat.', 'N'),
(49, 'Yulius Apip', 'Kenapa ndak pakek samsat keliling?', 'N'),
(50, 'Basgodo Solo', 'Mohon dibantu kalau sudah telat gimana?', 'N'),
(51, 'Mawanti', 'Berasa kayak dc aja, ditagih gini.', 'N'),
(52, 'RJ-Comunikasi', 'Tolong whatsappnya bukan hanya pajak.', 'N'),
(53, 'Heri Wicaksono', 'Gak buang2 anggaran kan ini?', 'N'),
(54, 'Ismail', 'Pelayanannya perlu ditingkatkan, kalau perlu ada sistem bayar online.', 'N'),
(55, 'Ernhy Triwulandari', 'Bakal lebih oke lagi kalau bisa bayar lewat whatsapp', 'N'),
(56, 'Mas Rid Wan', 'Sedikit mengganggu privasi', 'N'),
(57, 'Dek Nan', 'Kok nomor kendaraannya beda dengan punya saya?', 'N'),
(58, 'Marsih Handayani', 'Kalau telat gimana slur?', 'N'),
(59, 'Rani Mirza', 'jangan sampai program seperti ini hanya diawal saja, terus hilang entah kemana', 'N'),
(60, 'Niken Susanti', 'Pelayanan di kantornya masih lambat', 'N'),
(61, 'Ferygembus', 'Jangan ngingetin aja, tapi pelayanannya lama', 'N'),
(62, 'Herty Saputra', 'Sedikit terganggu', 'N'),
(63, 'Ri S Ta', 'wes koyo debt kolektor', 'N'),
(64, 'Isti Ana', 'Tukang tagih ini mah.', 'N'),
(65, 'Slamraisya', 'Bayar pajak dikejar-kejar rasanya', 'N'),
(66, 'Ratna Raybilq', 'Ini yang wa orang atau robot ya?', 'N'),
(67, 'Pipop Tri', 'Kok bulan kemarin saya gak ada wa ya?', 'N'),
(68, 'Octa Ciieen Cweekez CuueexZz', 'Kenapa tidak bikin aplikasi pajak lur?', 'N'),
(69, 'Saliim', 'jangan sampai data bocor!!!', 'N'),
(70, 'Musja Bin Suparno', 'Pajek pakai kk lama kok ditolak', 'N'),
(71, 'Maz Dennyz Plat AE', 'Saya sudah tidak megang motornya, sudah saya jual kok saya yang dapat whatsappnya?', 'N'),
(72, 'I-wan Wan', 'Kalau sudah dijual motornya apa perlu laporan ganti nomor lur? kan malas nerima wa pajek padahal dah ndak megang motornya', 'N'),
(73, 'Keysa Putri Ardita', 'Lebih bagus kalau ada info kebijakan juga, bukan hanya mengingatkan soal bayar pajaknya.', 'N'),
(74, 'Wahyana', 'Bayar mulu, sekali-sekali bebas pajak', 'N'),
(75, 'Muhammad Sahid', 'Bayar pajaknya lama di samsat', 'N'),
(76, 'Ayuk Tralala', 'tolong info lainnya juga', 'N'),
(77, 'Rohmad', 'Pelayanannya masih kurang', 'N'),
(78, 'Cungkring', 'tolong diingetinnya kalau bisa 3 hari sebelumnya, inget', 'N'),
(79, 'Retno Nursinta', 'Pengingat hanya berlaku 1 kali, perbaiki lagi ya', 'N'),
(80, 'Bejo Mulyo Waskitho', 'Request untuk pengingat dalam jangka waktu 2 minggu sblm jatuh tanggal tempo dong', 'N'),
(81, 'Rano Ardianto', 'Realitanya pembayaran masih terlalu jauh, perbanyak informasi jika telat membayar', 'N'),
(82, 'Bambang Alan', 'Maaf saya tetap masih telat membayar pajak', 'N'),
(83, 'Fitrah Handyn', 'Pembayaran saya masih saja terlambat walu sudah diingatkan', 'N'),
(84, 'Sis Sossis', 'Telat membayar tidak ada info?', 'N'),
(85, 'Rii Tariie Arii', 'Bagaimana agar mengetahui jumlah pajak yang akan dibayarkan?', 'N'),
(86, 'Yulius Irawan S', 'Jarak pengingat terlalu jauh. tidak membantu, bulan berikutnya saya lupa dan telat membayar', 'N'),
(87, 'Fajar Sugih Wiyono', 'walau sudah diingatkan tpi saya telat membayar karna dompet kosong hahahahaha', 'N'),
(88, 'Muqidi Panda WA', 'Kantor lain gimana ya?', 'N'),
(89, 'Ayu Lesta', 'Apa cuma pajak saja? kalau bisa yang lain dongg', 'N'),
(90, 'Parmin', 'Sayang belum bisa nanggapin whatsappnya', 'N'),
(91, 'Heru Wibowo', 'masih kurang, kalau bisa pertanyaan2 umum bisa dijawab di whatsapp', 'N'),
(92, 'Yeni Farida', 'giliran nagih cept', 'N'),
(93, 'Rian Bagoest', 'kalau saya gakmau nrima whatsappnya gmna????', 'N'),
(94, 'Triyanto', 'mersa kleganggu saya', 'N'),
(95, 'Teguh New', 'kejauhan kalau 1 bulan, masih lupa', 'N'),
(96, 'Nita Floris', 'tolong dong ditingkatkan lagi', 'N'),
(97, 'Wawan Tuhu', 'bayar dikantro lama rasanya!', 'N'),
(98, 'Budi Widiyanto', 'tolong pelayanannya ditingkatkan lagi', 'N'),
(99, 'Uutwijekso', 'coba lebih ditingkatkan lagi fiturnya.', 'N'),
(100, 'Shirie Setyo', 'Masih agak kurang kalau hanya lewat wa.', 'N'),
(101, 'M Faiz', 'masih kurang kalau belum bisa menanyakan kendaraan yang lain.', 'N'),
(102, 'Rudi Mark Mubarak', 'kenapa tidak lewat sms saja?', 'N'),
(103, 'Komariyah Suwoto', 'tidak semua orang punya wa', 'N'),
(104, 'Us Cho Prambudi', 'kalau yang tidak punya whatsapp gmna dong>', 'N'),
(105, 'Dwi Khansa', 'fiturnya masih kurang', 'N'),
(106, 'Ardhani Dhani', 'nek temenku yang gak punya wa piye lur?', 'N'),
(107, 'Widjianto Anto', 'kenapa tidak buat aplikasi saja? kalau kayak gini masih kurang interaktif', 'N'),
(108, 'Sintia Putri', 'bisa ndak buat ngecek yang lain?', 'N'),
(109, 'Uswatun Ummu Salamah', 'jangan hanya mengingatkan saja', 'N'),
(110, 'Agung Mila', 'pajak naik terus', 'N'),
(111, 'Alki Rahmawan', 'pelayanannya lama', 'N'),
(112, 'Rovi Hernandez', 'samsatnya kurang rapih', 'N'),
(113, 'Ririz de Azti', 'suka ganggu, karena kalau satu nomor dipake ke banyak motor', 'N'),
(114, 'Asha Whaegho Arena', 'kalau bisa wa nya jangan pagi2, bikin pusing pas berangkat kerja', 'N'),
(115, 'Kusuma Mbuls', 'jangan hanya mengingatkan sekali saja', 'N'),
(116, 'Heru Kholifin', 'mohon pembayarannya dipermudah dan dipercepat', 'N'),
(117, 'Wahyu Jaya', 'tolong dong pelayanan kantornya dipermudah', 'N'),
(118, 'Zahra Zam Hera', 'kalau telat kena denda berapa ya', 'N'),
(119, 'Sugeng Sugiarto', 'kalau ada pengumuman coba di umumkan lewat wa juga', 'N'),
(120, 'Septy Ramadhani', 'bisa ditingkatkan lagi dgn fitur lain', 'N'),
(121, 'Misaka Smd', 'kalau trlmbat gmna lur?', 'N'),
(122, 'Shegit Ariyanto', 'ganggu', 'N'),
(123, 'Puput Nasa', 'kalau data bocor gmna?', 'N'),
(124, 'Aris Yudho Wicaksana', 'manut wae lur', 'N'),
(125, 'Hartono', 'manut', 'N'),
(126, 'Agus Wahyudi', 'ngikut wes', 'N'),
(127, 'Mas Mus', 'apa datanya tidak dibocorkan', 'N'),
(128, 'Maz Syarif', 'smeoga data tidak bocor', 'N'),
(129, 'Bang Jay', 'jangan sampai ada korupsi', 'N'),
(130, 'Dery Fals', 'terkadang mengganggu', 'N'),
(131, 'Putra Kreasindo', 'kenapa harus 1 bln sebelumnya?', 'N'),
(132, 'Marry Agustina', 'biar ndak ditilang polisi', 'N'),
(133, 'Marsino', 'kurang setuju sih, merasa terganggu', 'N'),
(134, 'Desy Syahputra', 'jangan sampai dikorupsi', 'N'),
(135, 'HygherTest Rhoshy', 'samsat kelilingnya ditingkatkan lagiiii', 'N'),
(136, 'Bang W', 'jangan program2 saja, tapi pelayanannya juga ditingkatkan.', 'N'),
(137, 'Kokosidjoeko Soedjalie', 'kenapa tidak bisa untuk mengecek juga', 'N'),
(138, 'Veronika Mujiasih Defora', 'ini sih oke banget', 'N'),
(139, 'Yusha Prabowo', 'saya sih setuju aja', 'N'),
(140, 'Andreas', 'klaten semakin maju', 'N'),
(141, 'Farida Inti Lestari', 'mohon diperuntukkan juga ke perpajakan lainnya', 'N'),
(142, 'Tien Ibue Danish Permana', 'kalau bisa mengingatkannya beberapa kali', 'N'),
(143, 'Wahyu Tri Widadyo', 'mboten gadah duit lur', 'N'),
(144, 'Rengga Handa', 'Info Samsat keliling dong', 'N'),
(145, 'VevEn BeLlank', 'samsat kelilingnya sekalian diinfokan dong lur', 'N'),
(146, 'Bang Alip', 'samsat keliling mohon diperbanyak', 'N'),
(147, 'Agus Tebo', 'sayang antrinya banyak dan lama', 'N'),
(148, 'Shanty Dabokla', 'sing penting jalnaan ora rusak', 'N'),
(149, 'Centhierr Nthierr', 'Infone prosedur pajak kendaraan sekalian ganti plat', 'N'),
(150, 'Yusuf Budiyanto', 'info ne prosedur lur', 'N'),
(151, 'Devi Rahmadini', 'Aplikasi ini bagus, saya jadi ga kelupaan melulu buat perpanjang STNK.', 'P'),
(152, 'Yusril Idzati', 'Bagus sih, tapi coba kalau misal si pengingatnya ga cuma 1 kali 1 bulan sebelum masa tenggang.', 'P'),
(153, 'Oryza Sativa Ningrum', 'Aplikasinya ga jalan di hape saya. bintang 1/5', 'P'),
(154, 'Zakiyya El Muna', 'ini yang saya tunggu tunggu, dari dulu kok pemerintah ga pernah bikin kayak begini. Minta penduduk rajin pajak tapi ga ada yang ngingetin!', 'P'),
(155, 'Adnan Zein M', 'Mantap, fungsinya jalan tapi agak berat ya? mungkin optimasinya kurang bagus.', 'P'),
(156, 'Yoga', 'Cukup baik semoga dilanjutkan karena cukup membantu masyarakat umum dalam mengingatkan akan kewajiban membayar pajak kendaraan bermotor', 'P'),
(157, 'Leni Octavia', 'Alhamdulillah akhirnya ada aplikasi pajak. Saya selalu lupa kalau perpanjangan. Terima kasih!', 'P'),
(158, 'Rzka', 'Aplikasinya ga jalan. Saya buka ketutup terus. Benering dong.', 'P'),
(159, 'Pambayu Marifatulina', 'Mantap', 'P'),
(160, 'Adn Mujahid', 'Waktu itu saya juga pernha punya id kayak beginii. Tapi karena keterbatasan, gajadi deh. Untung ada yang bikin, mantap.', 'P'),
(161, 'Hani', 'Programnya bagus karena mengingatkan 1 bulan sebelum jatuh tempo pajak', 'P'),
(162, 'Nur', 'Bagus untuk dikembangkan agar tidak kelupaan saat jatuh tempo', 'P'),
(163, 'Atikah', 'Baik untuk dilanjutkan program ini', 'P'),
(164, 'Sri', 'Baik sih', 'P'),
(165, 'Atik', 'Pengingat jd gak kelupaan', 'P'),
(166, 'Rino', 'Baik buat sy yg pelupa', 'P'),
(167, 'Darmawan', 'Lanjutkan', 'P'),
(168, 'Rita', 'Siapa oke', 'P'),
(169, 'Yusup', 'Dipercepat', 'P'),
(170, 'Parman', 'Setuju', 'P'),
(171, 'Darman', 'Baik', 'P'),
(172, 'Ratna', 'Diteruskan', 'P'),
(173, 'Sugeng', 'Dipercepat', 'P'),
(174, 'Hesti Yulia Putri', 'Menurut saya dengan adanya pengingat pembayaran pajak kendaraan bermotor via whatsapp sangat membantu karena dapat tepat waktu dalam membayar pajak dan bisa mempersiapkan persyaratannya pada hari sebe', 'P'),
(175, 'Lutifiana Rohani', 'Ada sedikit bug di bagian sid menu yang ngeslid itu. Tapi lancar kok appnya.', 'P'),
(176, 'Adetya Rezki', 'Angka tagihannya berbeda dengan yang saya hitung secara manual.', 'P'),
(177, 'Bagaskoro Atmojo', 'Bekerja dengan baik. Sip!', 'P'),
(178, 'Ahmad Rozali', 'Saya dapat WAnya tapi ga ada tagihannya.', 'P'),
(179, 'Muhammad Priyambodo', 'Berguna banget emang. Kemarin saya hampir lupa, untung ada WAnya.', 'P'),
(180, 'Pandu Faiz Setiabudi', 'Sangat bermanfaat program ini . Dan bagus untuk di realisasikan. Tetapi harus banyak faktor yang diperhatikan juga terkait program ini, terkait keamanan data pengguna, dll', 'P'),
(181, 'Dama Anindya', 'Tanggapan saya terkait hal tersebut yaitu menurut saya sangat bagus apabila program tersebut dapt berjalan, karena menjadi notifikasi seseorang untuk dapat meminimalisir keterlambatan dalam membayar p', 'P'),
(182, 'Triska Marthiasari', 'Menurut saya sangat berguna apabila program tersebut dapat berjalan dengan baik, karena sangat membantu masyarakat untuk mengingat pembayaran pajak kendaraan sehingga dapat meminimalisir keterlambatan', 'P'),
(183, 'Yosef', 'Bagus, cocok buat yang sering kelupaan', 'P'),
(184, 'Melinda Tri', 'Mungkin bakal lebih bagus kalau whatsappnya bisa lebih interaktif', 'P'),
(185, 'Sutrisna S', 'Oke sih, tapi coba whatsappnya bisa digunakan untuk menanyakan kendaraan saya yang lain', 'P'),
(186, 'Nur Fatimah', 'Oke sih', 'P'),
(187, 'Rahma Wijaya', 'Klaten makin digitalisasi, keren', 'P'),
(188, 'Hafidz Khoirudin', 'Mantap deh, maju terus klaten', 'P'),
(189, 'Agoes Yunanto', 'Appsnya jalan di tempat saya, mantap.', 'P'),
(190, 'Soetopo', 'Terus ditingkatkan, makin jaya klaten', 'P'),
(191, 'Agus Triyanto', 'Maju terus klaten, makin modern', 'P'),
(192, 'Abdi', 'Ini baru namanya sebuah inovasi demi rakyat', 'P'),
(193, 'Djhony Walker', 'Wa iki akhire pajak dipakai untuk yang berguna, ga cuma dikorupsi.', 'P'),
(194, 'Agus Nugroho', 'Semoga bermanfaat buat semua yaa, ini aplikasi bagus.', 'P'),
(195, 'Sumardi', 'Kemaren hampir lupa bayar, Alhamdulillah diingetin lewat wa', 'P'),
(196, 'Dwi Hastuti', 'Whatsapp resmi kantor belum ada ya?', 'P'),
(197, 'Abduljamil', 'Mantep pun, klaten bersinar', 'P'),
(198, 'Rahma Dewi', 'Hampir aja kelupaan bayar, makasih samsat klaten', 'P'),
(199, 'Muh Maulana', 'Pelayanannya oke, terus ditingkatkan', 'P'),
(200, 'Mantriklatens', 'Tolong bisa disediakan tempat untuk mengganti nomor whatsappnya.', 'P'),
(201, 'Surani', 'Maju terus lur', 'P'),
(202, 'Warso', 'Sangat membantu karna terlalu sibuk belakangan ini', 'P'),
(203, 'Sholih Cinta', 'Membantu mengingatkan, perlu diingatkan 3x sebelum jatuh tempo', 'P'),
(204, 'Watic Asih Wahyunie', 'Baguss banget kok, semoga nggk bakal telat bayar lagi', 'P'),
(205, 'Arya Dwipangga', 'Lumayan membantu, tapi masih kurang membantu', 'P'),
(206, 'Putri Salsabila', 'Bagus, saya jadi lebih aware untuk membayar', 'P'),
(207, 'Inal Sundary', 'Alhamdulillah nggak jadi telat bayar. Thanks. Sangat membantu pokoknya', 'P'),
(208, 'Rafka Difta', 'Terimakasih. Informasi sesuai dengan kebutuhan untuk lebih mengingat jadwal pembayaran', 'P'),
(209, 'Yanto Cotty', 'Lebih baik jika pengingat 2 minggu sebelum jadwal pembayaran. Tapi sudah sangat membantu untuk di ingatkan', 'P'),
(210, 'Lantipto', 'Thanks a lot, sangat membantu banget pokoknya', 'P'),
(211, 'Rudiyanto Nainggolan', 'Pengingat ini sangat membantu karna saya pelupa dan sering banget telat bayar ihihihihi', 'P'),
(212, 'Dwik Brekele', 'Ya bisa membantu saya', 'P'),
(213, 'Diyahagustina', 'Bagus, lanjutkan dengan serius', 'P'),
(214, 'Bambang Satudelapanenam', 'Terimakasih sudah dibantu mengingatkan', 'P'),
(215, 'Fatma Fatma', 'Bagus', 'P'),
(216, 'Andri Kusyanto', 'Pengingat sangat baik, lanjutkan lebih baik lagi', 'P'),
(217, 'Dwi Listyarini', 'Sangat membantu, semoga selanjutnya lebih sering ri ingatkan lagi', 'P'),
(218, 'Dedi Alfian', 'Jika pengingat ini dikirim lebih sering akan sangat membantu, tapi ini sudah sangat membantu. Semangat mengembangkan dengan baik kagi', 'P'),
(219, 'Kamto', 'Ini membantu karna saya jadi nggk terlambay bayar jadinya', 'P'),
(220, 'Nasrullah hidayat', 'membantu saya alhamdulillah', 'P'),
(221, 'Hibban', 'Dengan adanya program ini, bisa meminimalisir orang kelupaan', 'P'),
(222, 'Yoga', 'Dilanjutkan, karena cukup membantu dalam mengingatkan akan pembayaran pajak kendaraan', 'P'),
(223, 'Ridho', 'Dilanjutkan, agar Masyarakat tidak lupa akan kewajiban membayar pajak kendaraan', 'P'),
(224, 'Yoga Rio Pambudi', 'Dilanjutkan, karena cukup memudahkan kepada masyarakat yang sering lupa akan kewajiban membayar pajak kendaraan bermotor', 'P'),
(225, 'Ramadhan', 'Mantap lur', 'P'),
(226, 'Rita m', 'Setuju', 'P'),
(227, 'Dian', 'Baik2', 'P'),
(228, 'Rahmat', 'Kalau syaa pribadi sih setuju saja kalau ada hal seperti ini, karena juga whatsaap itu banyak dipakai', 'P'),
(229, 'Lestari', 'Fitur seperti ini sangat membantu dikarenakan bisa membuat lebih sadar akan pajak', 'P'),
(230, 'Muhtar efendi', 'Kalau saya pribadi suka akan hal seperti ini, lebih berasa diperhatikan oleh pemerintah', 'P'),
(231, 'Farhan', 'Nek kayak gini sih setuju mawon', 'P'),
(232, 'Clone 22', 'oke2 saja sih', 'P'),
(233, 'Clone 23', 'oke sip!', 'P'),
(234, 'Winarni', 'Lanjutkan', 'P'),
(235, 'Yuri', 'Mantab', 'P'),
(236, 'Hariyanto', 'Setuju, bisa untuk mengingatkan tidak terlambat membayar pajak', 'P'),
(237, 'Dwi yatno', 'Menambah memudahkan informasi akan membayar pajak kendaraan', 'P'),
(238, 'Purwanto', 'Dipercepat', 'P'),
(239, 'Agung', 'Terimakasih di ingatkan lewat wa', 'P'),
(240, 'Siswanto', 'Efektiif', 'P'),
(241, 'Yanah', 'Good', 'P'),
(242, 'Yudi', 'Pajak jadi tidak terlambat', 'P'),
(243, 'Istiarti', 'Ya pengingat,Krn sering lupa', 'P'),
(244, 'Yamtono', 'Yang tadinya lupa pajak jadi ingat ingin bayar pajak', 'P'),
(245, 'Yustina Sri Hutami', 'Oke banget sih, mantap lah terus maju', 'P'),
(246, 'Kitut', 'Alhamdulillah makin maju klaten', 'P'),
(247, 'Zheyy', 'Emang mantap deh, maju terus pak ganjar', 'P'),
(248, 'Siti Nabila', 'sangat membantu buat ngingetin', 'P'),
(249, 'Ani Wahono', 'Wuelok tenan iki', 'P'),
(250, 'Tri Ri', 'Kaget aku dapet whatsapp, jebul disuruh bayar pajak', 'P'),
(251, 'Erick Fams', 'Terus tingkatkan, klaten bersinar', 'P'),
(252, 'Yeris', 'Lebih baik dari sebelum diingetin. thanks', 'P'),
(253, 'AuGust Ragiels', 'Semoga kedepan lebih baik lagi', 'P'),
(254, 'Sugiyono Bagong', 'Lumayan pokoke', 'P'),
(255, 'Alfarezi Alteza', 'Klaten kuto ku makin apik lan maju', 'P'),
(256, 'Agung Sutanto', 'Takiro hadiah, jebul kon mbayar. elok tenan pokok e', 'P'),
(257, 'Fitri Yuliastuti', 'Membantu sebagai pengingat. maju terus', 'P'),
(258, 'Tholle Broo', 'APik', 'P'),
(259, 'Christian Paidjo', 'Lebih oke lebih apik lebih sering sering yo', 'P'),
(260, 'Abdul Gafur', 'Alhamdulillah berkah', 'P'),
(261, 'Vriadi Jgy', 'Mantapsss gan', 'P'),
(262, 'Ning Lestari', 'Mengingatkan membayar sangat bagus, stop korupsi', 'P'),
(263, 'Yati Margiyanta', 'Klaten Bersih, Klaten Bersinar', 'P'),
(264, 'Wiyono Saputro', 'Lumayan', 'P'),
(265, 'Eny Triharyanti', 'Matursuwun, Pengingat mengingatkan dengan kegunaannya', 'P'),
(266, 'Sumarjono Joni', 'Semoga amanah dengan yang ada', 'P'),
(267, 'Rahayu', 'Rajin mengingatkan lagi', 'P'),
(268, 'Yanti Maryanti', 'Becik ketitik, mengingatkan sekali. suwun bos', 'P'),
(269, 'Ahmad Yusuf', 'membantu, terimakasih', 'P'),
(270, 'Maryamah', 'Lebih baik lagi jika bukan hanya mengingatkan, tapi memberi jumlah yang harus dibayarkan', 'P'),
(271, 'Suparno Mkt Joss', 'Suwun bos', 'P'),
(272, 'Priyono Asa', 'Mohon lebih di seringkan untuk mengingatkan', 'P'),
(273, 'Edy Rifky', 'Sudah bagus sak pol ee', 'P'),
(274, 'Agung Tri Wibowo', 'Klaten semakin maju', 'P'),
(275, 'Kautsar Gus T', 'Bagus bagus bagussss, tingkatkaannn', 'P'),
(276, 'Rima Sari', 'Alhamdulillah membantu <3', 'P'),
(277, 'Indira Putu', 'Semakin maju, semoga semakin lebih baik lagi', 'P'),
(278, 'Giarti Sutopo', 'Syukur sudah semakin membantu dengan diingatkan', 'P'),
(279, 'Ainul Rochmawati', 'lain kali lebih sering lagi dong diingetin nya', 'P'),
(280, 'New Nur Ahmad Wahid', 'bisa lah lumayan nih bro', 'P'),
(281, 'Adam Saja', 'Puji Tuhan semoga lebih baik lagi', 'P'),
(282, 'Sugeng Harsono', 'Kalaten membangun dan semakin sadar', 'P'),
(283, 'Revan Ardyanzah', 'Semoga antara hak dan kewajiban terus membaik dengan hal ini', 'P'),
(284, 'Bosscrypto', 'Pajak ku wes lunas, hati ku wes ora was was', 'P'),
(285, 'Rida Julianti', 'Bisa jadi pengingat', 'P'),
(286, 'Eko Prasetyo Wibowo', 'Makin maju klaten, maju terus.', 'P'),
(287, 'Ariadi', 'Mohon ditingkatkan pelayannanya, biar gak malas buat bayar', 'P'),
(288, 'Tok Til', 'Oke siap', 'P'),
(289, 'Sri Legowo', 'Klaten makin modern dan bersinar', 'P'),
(290, 'Edi Nugroho', 'Hampir aja kelupaan, untung diingetin.', 'P'),
(291, 'Kayla', 'Mantap lah klaten ini', 'P'),
(292, 'T Purnama', 'Coba deh kalau instansi lain juga ngingetinnya lewat wa.', 'P'),
(293, 'Thulip', 'Kalau emang bakal terus gini, oke sih. Makin modern dan ndak takut kelupaan lagi.', 'P'),
(294, 'Yeni Indraswati', 'Mantap sih maju terus ya klaten.', 'P'),
(295, 'Ncuss', 'Klaten go modern boss!!', 'P'),
(296, 'Dhesi Sandy Kristianto', 'Mantaps!', 'P'),
(297, 'Ontoseno Wisangeni', 'Saya suka, saya suka!', 'P'),
(298, 'Asih Giaraa', 'Nagih terusss!', 'P'),
(299, 'Irma Angely', 'saya setuju asal jangan sampai ada data bocor.', 'P'),
(300, 'Mei M P', 'Oke lah, makin maju klaten!', 'P'),
(301, 'Prayogy Phutunembahcunn', 'Mantap jiwa!', 'P'),
(302, 'Sri Dzaky', 'Lanjutkan lur!', 'P'),
(303, 'Roman Picisan', 'Gasss!', 'P'),
(304, 'Agung Plenthung', 'ini dari dulu saya tunggu!', 'P'),
(305, 'Mhazieh Zhiye Zhang Dhoeloe', 'Apik lah lur nek ngene ki!', 'P'),
(306, 'Andhi W', 'Maju terus!', 'P'),
(307, 'Anjar', 'Woah gak nyangka bakal diingetin di WA', 'P'),
(308, 'Nurul Hellokity', 'gaskeun!!', 'P'),
(309, 'Zanbrutal Zanbrutal', 'Ini baru berfikir maju!', 'P'),
(310, 'Agung Baskoro', 'maju terus slur!!', 'P'),
(311, 'Aris Gugun', 'nek aku sih yes slur', 'P'),
(312, 'Eko Riyanto', 'Bersama klaten bersinar!!', 'P'),
(313, 'Daniel Rustono', 'Pelayanannya itu perlu ditingkatkan lagii', 'P'),
(314, 'Aris Arifin', 'Kalau bisa dibikinkan aplikasi untuk pembayaran', 'P'),
(315, 'Lenk Q', 'Lama-lama semua online', 'P'),
(316, 'Sriyana Ana', 'Wah oke banget sih slur', 'P'),
(317, 'Bang Ucup', 'Harusnya sih dh gak ada alasan buat lupa kalau ada ini', 'P'),
(318, 'Arjuna Park Jayjund', 'Gak mungkin lupa sih', 'P'),
(319, 'Yazidlwuar', 'kalau lupa kebangeten', 'P'),
(320, 'Yunanik Trihapsari', 'mantap lah slur', 'P'),
(321, 'Dwik Saja', 'Gass terusss!', 'P'),
(322, 'Ardianto Wibowo', 'Sangat membantu', 'P'),
(323, 'Santoso Ken', 'Saya dukung sih kalau kayak gini', 'P'),
(324, 'Chen Cod', 'mantap jiwa!', 'P'),
(325, 'Suwarno Nano Nano', 'Kalau bisa diingetin juga kalau ada yang telat bayar', 'P'),
(326, 'Ridwan Dwi Haryanto', 'Gas', 'P'),
(327, 'MarReib Beel', 'okelah', 'P'),
(328, 'Desi Azhari', 'Kayaknya masih awalan ini ya.', 'P'),
(329, 'Vivio Zizio', 'Bersinar!!', 'P'),
(330, 'Teguh Priyanto', 'Anti mainstream', 'P'),
(331, 'Lilis W. Thony Kusuma', 'Manfaatkan aplikasi whatsapp, keren!!', 'P'),
(332, 'Sunardi Utomo', 'Muantep lur!', 'P'),
(333, 'Niya Agustin', 'Anti lupa sih', 'P'),
(334, 'Andi Alvano', 'Cara ngingetinnya oke sih', 'P'),
(335, 'RiyAnto', 'Bagus, sampai detail pembayarannya juga,.', 'P'),
(336, 'Pandu Balap', 'Okelah', 'P'),
(337, 'Tentrem Cahyono', 'Pak ganjar mantep', 'P'),
(338, 'Hasyim Ans', 'Siap lur', 'P'),
(339, 'Pesek Gendut', 'ra mungkin lali meneh', 'P'),
(340, 'Esti', 'wes jos gandos', 'P'),
(341, 'Solikin Stones', 'Klaten bersinar', 'P'),
(342, 'Tary Rhie Leztharry', 'maju terus dan bersinar klaten', 'P'),
(343, 'Budi Fiesta', 'gasssssss!!', 'P'),
(344, 'Triyono', 'oke sih, diingetin 1 bulan sebelumnya', 'P'),
(345, 'Naning Prihatin Daffa Aurelia', 'tingkatkan terus samsat klaten', 'P'),
(346, 'Erma Wahyu', 'makin canggih', 'P'),
(347, 'Wahyu Tri Wibowo', 'lama-lama bikin aplikasi sendiri sih ini kayaknya', 'P'),
(348, 'Yhanu Eddy Purwanto', 'kaget pas nerima whatsappnya, kirain ditagih utang ahahhaha', 'P'),
(349, 'Catur Wahyu', 'pengingatnya mantap', 'P'),
(350, 'Budiarti', 'makin maju terus', 'P'),
(351, 'Dannie Ziio', 'udah oke sih', 'P'),
(352, 'Esti', 'saya sih yes', 'P'),
(353, 'Eka Yunianta', 'goooodd', 'P'),
(354, 'Sri', 'Mantap jiwaa klaten!!', 'P'),
(355, 'Slamet Nugroho', 'Mantaps', 'P'),
(356, 'Wied Ndies', 'Klaten semakin canggih ternyata hohoho', 'P'),
(357, 'Cas Wanto', 'Peningkatan nih udh bisa di reminder lewat WA', 'P'),
(358, 'Adit Adit', 'Hidup dengan saling mengingatkan adalah hal yang baik. terimakasih.. lanjtukan', 'P'),
(359, 'Tri Waluyo', 'Klaten BISA', 'P'),
(360, 'Dian Eko Yogianti', 'Bukan hanya mengingatkan, tpai ini sebuah pembaruan yang baik untuk samsat klaten,,, terus maju', 'P'),
(361, 'Joko Purnomo', 'Tambahkan cashback lebih mantap', 'P'),
(362, 'Veri Pratiwi Handayani', 'Lumayan saya jadi lebih tepat waktu membayarnya', 'P'),
(363, 'Mitromartani', 'Mantp pokok e', 'P'),
(364, 'Abu Faiz Al Bayaty', 'Alhamdulillah', 'P'),
(365, 'Sri Yono', 'Dengan begini bisa membantu mengingatkan, seharusnya dari dulu', 'P'),
(366, 'Dedi', 'Samsat Klaten maju', 'P'),
(367, 'Verashop', 'Mengingatkan akan lebih membantu jika jarak dengan jadwal tempo tidak terlalu jauh', 'P'),
(368, 'Khur Khur ChelaluUntukmoeu', 'SUdah membantu', 'P'),
(369, 'Abdi Dalem', 'Bisa mengingatkan saya. terimakasih', 'P'),
(370, 'Wijislameto', 'Ya baguslah', 'P'),
(371, 'Fitriani Widhi Apsari', 'Pajak pajak terooossss, bayar teroooosss, jalan masih bolong bolong', 'P'),
(372, 'Muklis Nazaruddin', 'Bisa jadi inovasi jika pengingat jaraknya lebih deketan, btw makasih sudah diingatkan', 'P'),
(373, 'Carri Ica', 'Sedikit lagi pasti klaten semakin baik, masyarakat patuh pemerintahan harus bagus', 'P'),
(374, 'Mulyonoaja', 'Terimakasih, saya suka dengan pembaruan pengingat seperti ini', 'P'),
(375, 'Kang Irfan Njul', 'udah makin oke sih kalau kayak gini', 'P'),
(376, 'Mas Jolang', 'Bersinar terusss', 'P'),
(377, 'Andre Nugraha', 'maju terus kalten', 'P'),
(378, 'Akthar Zavier Nalendra', 'gas terus klatenn', 'P'),
(379, 'Kang Yoto', 'semoga tdk buang2 anggaran', 'P'),
(380, 'Eko Sujono', 'pelayanannya tditingaktkan', 'P'),
(381, 'Elyk Soer Djanto', 'oke sih', 'P'),
(382, 'Mariyana', 'mantap deh', 'P'),
(383, 'Bintang Bersinar', 'kria2 ini sampai kapan ya', 'P'),
(384, 'Elyas Whydhy Anto', 'gini kan oke, jadi makin inget buat bayar pajak', 'P'),
(385, 'Pupusing Donnyo', 'Suka sih kalau ada pengingat lewat wa gini, soalnya jadi lebih sadar buat bayar aja', 'P'),
(386, 'Vhelix Dwiyanto', 'Pokoke mantep lur.', 'P'),
(387, 'Aan Febrianto', 'klaten makin joss', 'P'),
(388, 'Riyanto Sofyan', 'waahh oke sih kalau kayak gini', 'P'),
(389, 'Jumaeni Mardi Suwito', 'makin mantap lah pokok e', 'P'),
(390, 'Tri Wahana Thekopites', 'samsat klaten makin modern', 'P'),
(391, 'Muhammad Taufik', 'Semoga terus lanjut biar maki bagus', 'P'),
(392, 'Ekanzha Wahyudi', 'setuju banget kalau kayak gini.', 'P'),
(393, 'Eko Santoso', 'Maju terus klaten', 'P'),
(394, 'Febry Nanda', 'tingkatkan', 'P'),
(395, 'Ninnick Ernawaty', 'Makin oke lah', 'P'),
(396, 'Hapshary ANaya KW', 'gak nyangka langsung lewat wa', 'P'),
(397, 'Ari Wibowo', 'bagus biar lebih sadar pajak', 'P'),
(398, 'Wong Deso', 'lebih oke sih kalau kayak gini', 'P'),
(399, 'Shimens Sanjaya', 'pokoke makin oke lah', 'P'),
(400, 'Agus Anjas Setiawan', 'semoga proses di samsatnya juga lancar', 'P'),
(401, 'Ardiansyah Lovel', 'semoga makin oke sih', 'P'),
(402, 'Mbah Atemoo', 'maju terus pokok e klaten', 'P'),
(403, 'Sugix Yanto', 'bagus', 'P'),
(404, 'Thole Havidz', 'teruskan', 'P'),
(405, 'Ariwibowo', 'tingkatkan', 'P'),
(406, 'Unnik Nur Aisyah', 'semoga memang dapat memudahkan juga kedepannya', 'P'),
(407, 'Ajab Januri', 'mantap lah lur', 'P'),
(408, 'Jak Ka', 'ayo terus klaten', 'P'),
(409, 'Dian Rahmadi', 'fitur kayak gini yang ditunggu-tunggu. mantap lah pokok e', 'P'),
(410, 'Ginarno', 'maju terus klaten', 'P'),
(411, 'Ervin Ny', 'terus ditingkatkan lur', 'P'),
(412, 'Sarni Seera', 'mengganggu', 'P'),
(413, 'Yoga Danis', 'semoga lanjut terus', 'P'),
(414, 'Fix Too Daffa', 'bagus, biar pada bayar pajak', 'P'),
(415, 'Wawandarmawan', 'pajak memang penting, tingkatkan klaten', 'P'),
(416, 'Adipati Doel Kent', 'samsat klaten joss', 'P'),
(417, 'Bilqis Anindita', 'wes makin oke lah', 'P'),
(418, 'Muhamad Irawan', 'terus klaten', 'P'),
(419, 'Sani', 'yuk gas terus klaten', 'P'),
(420, 'Mak Ito Marsinah', 'pak ganjar maju presidn joss', 'P'),
(421, 'Said Rahman', 'mantap lah', 'P'),
(422, 'Qoyyum Prasetya', 'terimakasih telah mengingatkan', 'P'),
(423, 'Bamz Alprima', 'gak nyangka bakal pakai wa', 'P'),
(424, 'Adhi Darrma', 'oke sih kalau kayak gini', 'P'),
(425, 'Sri Purnomo', 'biar sadar bayar pajak, maju terus', 'P'),
(426, 'Agus Setyawan', 'ini sih makin oke', 'P'),
(427, 'Menik Rohaya', 'klaten terbaik', 'P'),
(428, 'Bang Sup', 'maju terus klaten', 'P'),
(429, 'Lifah Buke Bian', 'luar biasa klaten', 'P'),
(430, 'Mas Basuki', 'ok sih', 'P'),
(431, 'Sarno', 'saya oke saja', 'P'),
(432, 'Windari Windari', 'mantap lah kalau kyak gni', 'P'),
(433, 'Tutik Riyanti', 'luar biasa', 'P'),
(434, 'Reni Azizah', 'mantap lah lur', 'P'),
(435, 'Hafiz Saifullah', 'yes', 'P'),
(436, 'Haryoni', 'klaten bersinar terus', 'P'),
(437, 'Vietrieana', 'makin oke kalau begini', 'P'),
(438, 'Landung Mawardi', 'mntp lah pokoke', 'P'),
(439, 'Noah Setiawan', 'gas terus lur', 'P'),
(440, 'Dwixs Sekar Cuah Karangdowo', 'makin oke aja lah', 'P'),
(441, 'Maryadi Adi', 'setuju mawon kalau ada kayak begini', 'P'),
(442, 'Johan Putra', 'tingkatkan terus', 'P'),
(443, 'Wirchun Chahyati', 'dikembangkan terus', 'P'),
(444, 'Mz dodo Rafi Aqila', 'makin mantap sih', 'P'),
(445, 'Ekanada Ekanada', 'terus ditingkatkan', 'P'),
(446, 'Lisa Shandy', 'teruskan', 'P'),
(447, 'Joko Uux', 'ok', 'P'),
(448, 'Ndo Weng', 'gas', 'P'),
(449, 'Yoga Pratama', 'maju terus', 'P'),
(450, 'Apa Aja Ada Kuq', 'klaten mantap', 'P'),
(451, 'Davian Alfares', 'samsat makin mdoern', 'P'),
(452, 'Joko Riyanto', 'luar biasa', 'P'),
(453, 'Kristian Muladi', 'ini sih makin maju', 'P'),
(454, 'Satrio Kebal Wirank', 'saya sih sangat setuju kalau ada hal seperti ini', 'P'),
(455, 'Odik Rengganis', 'luar biasa lah klaten', 'P'),
(456, 'Anthiq Thox', 'gara2 ini saya hampir kelupaan, terimakasih', 'P'),
(457, 'Moeh Seno Widagdo', 'matur suwun', 'P'),
(458, 'Mawar Grosir Tas', 'terimakasih klaten', 'P'),
(459, 'Candra', 'samsat klaten joss', 'P'),
(460, 'Zainab Umu', 'makin oke lah pokok e', 'P'),
(461, 'Slamet Riyadi Riyadi', 'jos poll', 'P'),
(462, 'Tok Tak', 'luar baisa klaten', 'P'),
(463, 'Ifa Musafik', 'saya sih suka kalau begini', 'P'),
(464, 'Arif Sulistyanto', 'ini luar biasa', 'P'),
(465, 'Edi Santoso', 'Alhamdulillah makin modern', 'P'),
(466, 'Reyha Rhama', 'saya suka dengan program seperti ini', 'P'),
(467, 'Feli Santo', 'oke banget', 'P'),
(468, 'Dewi Sekar Arum', 'sip deh', 'P'),
(469, 'Cuah Dhuableg Dewe Hanono', 'suwun', 'P'),
(470, 'Bagong Anjay', 'saya sih oke kalau fitur kyak gini ada', 'P'),
(471, 'Z-yucx', 'pokok e jos', 'P'),
(472, 'Harry Paningit', 'manut lah', 'P'),
(473, 'Napp', 'kalau gini makin suka rajin bayar', 'P'),
(474, 'Risski', 'stuju mawon', 'P'),
(475, 'Purwanto Wanto', 'apik lah', 'P'),
(476, 'Tjioe Sien', 'makin jos nek ngene', 'P'),
(477, 'Elia Rosita', 'mantap lah', 'P'),
(478, 'Sri Guntari', 'kelingan pajek mergane di wa', 'P'),
(479, 'Utami', 'joss pokok e', 'P'),
(480, 'Wiji Hartanti', 'aku sih yes', 'P'),
(481, 'Wahyono Agis', 'gini kan makin mantep', 'P'),
(482, 'Relia Vania', 'tingkatkan terus', 'P'),
(483, 'Azzahra Husna S', 'saya dukung', 'P'),
(484, 'Antoni Didik', 'Pengingat macam ini menurut saya cukup baik', 'P'),
(485, 'Winnie Poetra', 'kalau ada hal seperti ini seharusnya masyarakat akan lebih sadar akan pajak kendaraan', 'P'),
(486, 'Ichan Saputra', 'memang orang indonesia perlu diingatkan, dan menurut saya ini cara yang bagus', 'P'),
(487, 'Russtam Ayuex', 'whatsapp banyak yang pakai sih, jadi menurut saya bagus', 'P'),
(488, 'Rika Afri', 'oke banget sih', 'P'),
(489, 'Anjar Kla-x', 'kalau begini sudah tidak ada alasan lagi lupa bayar pajak', 'P'),
(490, 'Telu Limo Siji', 'semakin maju klaten', 'P'),
(491, 'Andik Apriyanto', 'semoga bisa ditingkatkan kembali', 'P'),
(492, 'Jumarrie', 'kalau begini lebih oke', 'P'),
(493, 'Lusya Sriyati', 'bisa dibilang cukup baik', 'P'),
(494, 'Eko Tombogelo', 'saya sih oke2 saja', 'P'),
(495, 'Widodo As', 'selama pelayanan baik, saya sih setuju saja', 'P'),
(496, 'Eko Suryanto', 'pengingat melalui whatsapp, menurut saya perlu', 'P'),
(497, 'Siti Suharjanti', 'cukup senang karena diingatkan melalui wa', 'P'),
(498, 'Vajar Tri Wahyuni', 'saya setuju', 'P'),
(499, 'Tato Tra', 'semakin sadar soal pajak', 'P'),
(500, 'Millo Lachata', 'mantap', 'P');
COMMIT;
